### ISSUE TITLE
`KeyError: '1.1.6'` parsing track.txt

### ISSUE THREAD

**Issue by mprins** [openstreetcam/upload-scripts#32]
trying to parse a track.txt file for coordinates I get a `KeyError: '1.1.6'` using the `parseCsv()` function from upload_photos.py

I Looked at the upload_video script but that has 1.1.5 as the hghest version

**Comment by bogdan-telenav** [comment]
@mprins The problem is that there exist a new version for track.txt, and i didn't updated on github. I will updated this in some day's

**Comment by mprins** [comment]
right now I'm using the line in https://github.com/mprins/upload-scripts/blob/003c174808ce6aacf363f00f91529dda05fed39b/track_to_gpx/track_to_gpx.py#L51 (part of #33) which seems to work for me, but I may be missing stuff

**Comment by bogdan-telenav** [comment]
This is not correct, this data has been changed within metadata internal protocol.Since version 1.0.8 was only for images, version 1.1.6 is using images/videos so the there is a new index for videos. This is a correct example for 1.1.6: https://github.com/openstreetcam/upload-scripts/blob/master/upload_osv_videos/upload_video.py#L310

**Comment by bogdan-telenav** [comment]
This is fixed
