### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by naoliv** [openstreetcam/upload-scripts#60]
I've followed all instructions [from here](https://github.com/openstreetcam/upload-scripts#requirements), authorized the app and then it simply does nothing.

For example, if I run `python upload_photos.py -p /arquivos/osc/OSV/SEQ_1535382073557/` it seems to just quit, without any error, warning or anything else (including not uploading the files).

The exit code is `0`.

What can I do to help in debugging this, please?

**Comment by bogdans-telenav** [comment]
@naoliv I am guessing this is a android made sequence with the latest app version. It has been some time since we updated the scripts and most probably they are not able to get the required info from the latest android sequences. I am working on a new version of scripts in witch we will fix the major flaws of the current ones (upload, sequence discovery). 
If i find that is just a matter of updating some small stuff i will post a fix for your issue. But either way i will keep you posted.

**Comment by naoliv** [comment]
Great, thanks!

**Comment by bogdans-telenav** [comment]
Finally it is done! If you find any issue with the current version please provide feedback.
